# Generated by Django 5.0.2 on 2024-02-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_publisehd',
            field=models.BooleanField(default=False, help_text='Este campo publica o artigo.'),
        ),
    ]
