# Generated by Django 5.0.2 on 2024-02-26 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_category_post_content_post_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2024, 2, 26, 15, 49, 2, 476112, tzinfo=datetime.timezone.utc)),
        ),
    ]
