# Generated by Django 5.0.2 on 2024-02-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_publisehd',
        ),
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Este campo publica o artigo.'),
        ),
    ]
